server.port: 8085
spring:
  cloud.stream:
    function:
      definition: inventoryProcessor
    bindings:
      inventoryProcessor-in-0:
        destination: order-event
        group: inventory-group
      inventoryProcessor-out-0:
        destination: inventory-event
