server.port: 8084
spring:
  cloud.stream:
    function:
      definition: paymentProcessor
    bindings:
      paymentProcessor-in-0:
        destination: order-event
        group: payment-group
      paymentProcessor-out-0:
        destination: payment-event