spring:
  cloud.stream:
    kafka.binder.brokers: cuongpc.localdomain:9092
    function:
      definition: paymentProcessor
    bindings:
      paymentProcessor-in-0:
        destination: order-event
      paymentProcessor-out-0:
        destination: payment-event
  datasource:
    url: jdbc:h2:file:./db/paymentDb
    driverClassName: org.h2.Driver
    username: sa
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties.hibernate:
      validator.apply_to_ddl: false
      format_sql: true
  h2.console:
    enabled: true
    path: /h2-console